function create_buck_dual_loop_demo()
%CREATE_BUCK_DUAL_LOOP_DEMO Build an averaged Buck converter with dual PI loops.

model = "pid_ai_buck_dual_loop_demo";
modelFile = fullfile(pwd, model + ".slx");
if bdIsLoaded(model)
    try
        set_param(model, "FastRestart", "off");
    catch
    end
    close_system(model, 0);
end
if isfile(modelFile)
    delete(modelFile);
end

new_system(model);
open_system(model);
localConfigureWorkspace(model);

add_block("simulink/Sources/Constant", model + "/Voltage_Reference", ...
    "Value", "Buck_Vref", "Position", [30 80 80 110]);
add_block("simulink/Math Operations/Sum", model + "/Voltage_Error", ...
    "Inputs", "+-", "Position", [120 75 145 115]);
add_block("simulink/Continuous/PID Controller", model + "/Outer_Voltage_PI", ...
    "P", "Buck_Kpv_Init", "I", "Buck_Kiv_Init", "D", "0", "N", "100", ...
    "Position", [185 70 285 120]);
add_block("simulink/Discontinuities/Saturation", model + "/Current_Reference_Limit", ...
    "LowerLimit", "0", "UpperLimit", "Buck_Current_Limit", ...
    "Position", [325 75 375 115]);
add_block("simulink/Math Operations/Sum", model + "/Current_Error", ...
    "Inputs", "+-", "Position", [415 75 440 115]);
add_block("simulink/Continuous/PID Controller", model + "/Inner_Current_PI", ...
    "P", "Buck_Kpi_Init", "I", "Buck_Kii_Init", "D", "0", "N", "100", ...
    "Position", [480 70 580 120]);
add_block("simulink/Discontinuities/Saturation", model + "/Duty_Cycle_Limit", ...
    "LowerLimit", "0", "UpperLimit", "Buck_Duty_Max", ...
    "Position", [620 75 670 115]);
add_block("simulink/Sources/Step", model + "/Input_Voltage", ...
    "Time", "Buck_Vin_StepTime", "Before", "Buck_Vin_Nominal", ...
    "After", "Buck_Vin_Disturbed", "SampleTime", "0", ...
    "Position", [620 160 670 190]);
add_block("simulink/Sources/Step", model + "/Load_Conductance", ...
    "Time", "Buck_Load_StepTime", "Before", "1/Buck_Load_R1", ...
    "After", "1/Buck_Load_R2", "SampleTime", "0", ...
    "Position", [620 225 670 255]);

plant = model + "/Buck_Power_Stage";
add_block("simulink/Ports & Subsystems/Subsystem", plant, ...
    "Position", [730 65 890 260]);
Simulink.SubSystem.deleteContents(plant);
localBuildPowerStage(plant);

localAddLog(model, "Log_r", "r", [930 20 1000 50]);
localAddLog(model, "Log_y", "y", [930 75 1000 105]);
localAddLog(model, "Log_u", "u", [700 20 770 50]);
localAddLog(model, "Log_iL", "iL", [930 130 1000 160]);

add_line(model, "Voltage_Reference/1", "Voltage_Error/1");
add_line(model, "Voltage_Error/1", "Outer_Voltage_PI/1");
add_line(model, "Outer_Voltage_PI/1", "Current_Reference_Limit/1");
add_line(model, "Current_Reference_Limit/1", "Current_Error/1");
add_line(model, "Current_Error/1", "Inner_Current_PI/1");
add_line(model, "Inner_Current_PI/1", "Duty_Cycle_Limit/1");
add_line(model, "Duty_Cycle_Limit/1", "Buck_Power_Stage/1");
add_line(model, "Input_Voltage/1", "Buck_Power_Stage/2");
add_line(model, "Load_Conductance/1", "Buck_Power_Stage/3");
add_line(model, "Buck_Power_Stage/1", "Voltage_Error/2", "autorouting", "on");
add_line(model, "Buck_Power_Stage/2", "Current_Error/2", "autorouting", "on");
add_line(model, "Voltage_Reference/1", "Log_r/1", "autorouting", "on");
add_line(model, "Buck_Power_Stage/1", "Log_y/1", "autorouting", "on");
add_line(model, "Duty_Cycle_Limit/1", "Log_u/1", "autorouting", "on");
add_line(model, "Buck_Power_Stage/2", "Log_iL/1", "autorouting", "on");

set_param(model, "StopTime", "0.3", "Solver", "ode23t", ...
    "MaxStep", "1e-4", "RelTol", "1e-5", "FastRestart", "off");
set_param(model, "Description", ...
    "Averaged Buck converter with outer voltage PI and inner current PI control.");
save_system(model, modelFile);
fprintf("Created Buck dual-loop PID demo: %s\n", modelFile);
end

function localConfigureWorkspace(model)
workspace = get_param(model, "ModelWorkspace");
values = struct( ...
    "Buck_Vref", 12, ...
    "Buck_Vin_Nominal", 24, ...
    "Buck_Vin_Disturbed", 20, ...
    "Buck_Vin_StepTime", 0.08, ...
    "Buck_Load_R1", 6, ...
    "Buck_Load_R2", 3, ...
    "Buck_Load_StepTime", 0.12, ...
    "Buck_L", 470e-6, ...
    "Buck_C", 470e-6, ...
    "Buck_RL", 0.08, ...
    "Buck_Current_Limit", 8, ...
    "Buck_Duty_Max", 0.95, ...
    "Buck_Kpv_Init", 0.08, ...
    "Buck_Kiv_Init", 8, ...
    "Buck_Kpi_Init", 0.04, ...
    "Buck_Kii_Init", 8);
names = fieldnames(values);
for index = 1:numel(names)
    assignin(workspace, names{index}, values.(names{index}));
end
end

function localBuildPowerStage(plant)
add_block("simulink/Ports & Subsystems/In1", plant + "/duty", ...
    "Port", "1", "Position", [25 45 55 65]);
add_block("simulink/Ports & Subsystems/In1", plant + "/vin", ...
    "Port", "2", "Position", [25 95 55 115]);
add_block("simulink/Ports & Subsystems/In1", plant + "/load_g", ...
    "Port", "3", "Position", [25 250 55 270]);
add_block("simulink/Math Operations/Product", plant + "/Averaged_Switch_Voltage", ...
    "Inputs", "**", "Position", [95 55 130 100]);
add_block("simulink/Math Operations/Sum", plant + "/Inductor_Voltage", ...
    "Inputs", "+--", "Position", [185 70 210 120]);
add_block("simulink/Math Operations/Gain", plant + "/Inverse_Inductance", ...
    "Gain", "1/Buck_L", "Position", [250 75 315 115]);
add_block("simulink/Continuous/Integrator", plant + "/Inductor_Current_State", ...
    "InitialCondition", "0", "Position", [355 75 385 115]);
add_block("simulink/Math Operations/Gain", plant + "/Inductor_Resistance", ...
    "Gain", "Buck_RL", "Position", [355 150 420 185]);
add_block("simulink/Math Operations/Sum", plant + "/Capacitor_Current", ...
    "Inputs", "+-", "Position", [465 220 490 260]);
add_block("simulink/Math Operations/Gain", plant + "/Inverse_Capacitance", ...
    "Gain", "1/Buck_C", "Position", [530 220 595 260]);
add_block("simulink/Continuous/Integrator", plant + "/Output_Voltage_State", ...
    "InitialCondition", "0", "Position", [635 220 665 260]);
add_block("simulink/Math Operations/Product", plant + "/Load_Current", ...
    "Inputs", "**", "Position", [355 250 395 290]);
add_block("simulink/Ports & Subsystems/Out1", plant + "/vout", ...
    "Port", "1", "Position", [735 225 765 245]);
add_block("simulink/Ports & Subsystems/Out1", plant + "/iL", ...
    "Port", "2", "Position", [735 80 765 100]);

add_line(plant, "duty/1", "Averaged_Switch_Voltage/1");
add_line(plant, "vin/1", "Averaged_Switch_Voltage/2");
add_line(plant, "Averaged_Switch_Voltage/1", "Inductor_Voltage/1");
add_line(plant, "Output_Voltage_State/1", "Inductor_Voltage/2", "autorouting", "on");
add_line(plant, "Inductor_Current_State/1", "Inductor_Resistance/1");
add_line(plant, "Inductor_Resistance/1", "Inductor_Voltage/3", "autorouting", "on");
add_line(plant, "Inductor_Voltage/1", "Inverse_Inductance/1");
add_line(plant, "Inverse_Inductance/1", "Inductor_Current_State/1");
add_line(plant, "Inductor_Current_State/1", "Capacitor_Current/1", "autorouting", "on");
add_line(plant, "Output_Voltage_State/1", "Load_Current/1", "autorouting", "on");
add_line(plant, "load_g/1", "Load_Current/2");
add_line(plant, "Load_Current/1", "Capacitor_Current/2");
add_line(plant, "Capacitor_Current/1", "Inverse_Capacitance/1");
add_line(plant, "Inverse_Capacitance/1", "Output_Voltage_State/1");
add_line(plant, "Output_Voltage_State/1", "vout/1");
add_line(plant, "Inductor_Current_State/1", "iL/1");
end

function localAddLog(model, blockName, variableName, position)
add_block("simulink/Sinks/To Workspace", model + "/" + blockName, ...
    "VariableName", variableName, "SaveFormat", "Timeseries", ...
    "MaxDataPoints", "inf", "Position", position);
end